
export default {
    api: {
        protocol: "http",
        host: "localhost",
        port: "3001"
    },
    emoji_list: [
        "clown-face_1f921.png",
        "extraterrestrial-alien_1f47d.png",
        "face-palm_1f926.png",
        "face-savouring-delicious-food_1f60b.png",
        "face-screaming-in-fear_1f631.png",
        "face-throwing-a-kiss_1f618.png",
        "face-with-cowboy-hat_1f920.png",
        "face-with-look-of-triumph_1f624.png",
        "face-with-medical-mask_1f637.png",
        "face-with-monocle_1f9d0.png",
        "face-with-open-mouth_1f62e.png",
        "face-with-rolling-eyes_1f644.png",
        "face-with-stuck-out-tongue_1f61b.png",
        "face-with-stuck-out-tongue-and-winking-eye_1f61c.png",
        "face-with-tears-of-joy_1f602.png",
        "flushed-face_1f633.png",
        "ghost_1f47b.png",
        "grinning-cat-face-with-smiling-eyes_1f638.png",
        "grinning-face_1f600.png",
        "grinning-face-with-one-large-and-one-small-eye_1f92a.png",
        "grinning-face-with-smiling-eyes_1f601.png",
        "grinning-face-with-star-eyes_1f929.png",
        "hear-no-evil-monkey_1f649.png",
        "jack-o-lantern_1f383.png",
        "lion-face_1f981.png",
        "lying-face_1f925.png",
        "man-shrugging_1f937-200d-2642-fe0f.png",
        "money-mouth-face_1f911.png",
        "monkey-face_1f435.png",
        "mouse-face_1f42d.png",
        "nerd-face_1f913.png",
        "pig-face_1f437.png",
        "pile-of-poo_1f4a9.png",
        "robot-face_1f916.png",
        "see-no-evil-monkey_1f648.png",
        "shrug_1f937.png",
        "slightly-frowning-face_1f641.png",
        "slightly-smiling-face_1f642.png",
        "smiling-face-with-halo_1f607.png",
        "smiling-face-with-heart-shaped-eyes_1f60d.png",
        "smiling-face-with-open-mouth_1f603.png",
        "smiling-face-with-open-mouth-and-cold-sweat_1f605.png",
        "smiling-face-with-open-mouth-and-smiling-eyes_1f604.png",
        "smiling-face-with-open-mouth-and-tightly-closed-eyes_1f606.png",
        "smiling-face-with-smiling-eyes_1f60a.png",
        "smiling-face-with-sunglasses_1f60e.png",
        "smirking-face_1f60f.png",
        "tiger-face_1f42f.png",
        "winking-face_1f609.png",
        "woman-facepalming_1f926-200d-2640-fe0f.png"
    ]
};